import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <a href="/">
          <Button variant="ghost" className="mb-6">
            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Home
          </Button>
        </a>
        
        <h1 className="text-4xl font-serif font-bold text-foreground mb-6">
          Privacy Policy
        </h1>
        
        <div className="prose prose-slate max-w-none text-foreground">
          <p className="text-lg mb-4">
            Musicatnip LLC ("us", "we", or "our") operates the site(s) thesheetsexpert.com.
          </p>
          
          <p className="mb-4">
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
          </p>
          
          <p className="mb-4">
            We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from thesheetsexpert.com.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Definitions</h2>
          
          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Service</h3>
          <p className="mb-4">
            Service is the thesheetsexpert.com website operated by Musicatnip LLC
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Personal Data</h3>
          <p className="mb-4">
            Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Usage Data</h3>
          <p className="mb-4">
            Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Cookies</h3>
          <p className="mb-4">
            Cookies are small pieces of data stored on your device (computer or mobile device).
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Data Controller</h3>
          <p className="mb-4">
            Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
          </p>
          <p className="mb-4">
            For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Data Processors (or Service Providers)</h3>
          <p className="mb-4">
            Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
          </p>
          <p className="mb-4">
            We may use the services of various Service Providers in order to process your data more effectively.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Data Subject (or User)</h3>
          <p className="mb-4">
            Data Subject is any living individual who is using our Service and is the subject of Personal Data.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Information Collection And Use</h2>
          <p className="mb-4">
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Types of Data Collected</h3>
          
          <h4 className="text-lg font-serif font-bold mt-4 mb-2">Personal Data</h4>
          <p className="mb-4">
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>
          <p className="mb-4">
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send, by managing your notification settings in your account, or by contacting us.
          </p>

          <h4 className="text-lg font-serif font-bold mt-4 mb-2">Usage Data</h4>
          <p className="mb-4">
            We may also collect information about how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <h4 className="text-lg font-serif font-bold mt-4 mb-2">Tracking & Cookies Data</h4>
          <p className="mb-4">
            We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
          </p>
          <p className="mb-4">
            Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
          </p>
          <p className="mb-4">
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p className="mb-4">Examples of Cookies we use:</p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
            <li><strong>Advertising Cookies.</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
          </ul>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Use of Data</h2>
          <p className="mb-4">Musicatnip LLC uses the collected data for various purposes:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
          </ul>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>
          <p className="mb-4">
            If you are from the European Economic Area (EEA), Musicatnip LLC legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
          </p>
          <p className="mb-4">Musicatnip LLC may process your Personal Data because:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
            <li>To comply with the law</li>
          </ul>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Retention of Data</h2>
          <p className="mb-4">
            Musicatnip LLC will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          <p className="mb-4">
            Musicatnip LLC will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Transfer Of Data</h2>
          <p className="mb-4">
            Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
          </p>
          <p className="mb-4">
            If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
          </p>
          <p className="mb-4">
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          </p>
          <p className="mb-4">
            Musicatnip LLC will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Disclosure Of Data</h2>
          
          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Business Transaction</h3>
          <p className="mb-4">
            If Musicatnip LLC is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Disclosure for Law Enforcement</h3>
          <p className="mb-4">
            Under certain circumstances, Musicatnip LLC may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Legal Requirements</h3>
          <p className="mb-4">Musicatnip LLC may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>To comply with a legal obligation</li>
            <li>To protect and defend the rights or property of Musicatnip LLC</li>
            <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>To protect the personal safety of users of the Service or the public</li>
            <li>To protect against legal liability</li>
          </ul>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Security Of Data</h2>
          <p className="mb-4">
            The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">"Do Not Track" Signals</h2>
          <p className="mb-4">
            We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
          </p>
          <p className="mb-4">
            You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
          <p className="mb-4">
            If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Musicatnip LLC aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
          </p>
          <p className="mb-4">
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
          </p>
          <p className="mb-4">In certain circumstances, you have the following data protection rights:</p>
          <ul className="list-disc pl-6 mb-4">
            <li><strong>The right to access, update or to delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
            <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
            <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
            <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
            <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
            <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Musicatnip LLC relied on your consent to process your personal information.</li>
          </ul>
          <p className="mb-4">
            Please note that we may ask you to verify your identity before responding to such requests.
          </p>
          <p className="mb-4">
            You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Service Providers</h2>
          <p className="mb-4">
            We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
          </p>
          <p className="mb-4">
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Analytics</h3>
          <p className="mb-4">
            We may use third-party Service Providers to monitor and analyze the use of our Service.
          </p>
          <p className="mb-4">
            <strong>Google Analytics</strong><br />
            Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
          </p>
          <p className="mb-4">
            You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
          </p>
          <p className="mb-4">
            For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/" className="text-primary hover:underline">http://www.google.com/intl/en/policies/privacy/</a>
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Advertising</h3>
          <p className="mb-4">
            We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.
          </p>
          <p className="mb-4">
            <strong>Google Ads Cookie</strong><br />
            Google, as a third party vendor, uses cookies to ads to a targeted audience. Google's use of their cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet.
          </p>
          <p className="mb-4">
            You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: <a href="http://www.google.com/ads/preferences/" className="text-primary hover:underline">http://www.google.com/ads/preferences/</a>
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Links To Other Sites</h2>
          <p className="mb-4">
            Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          </p>
          <p className="mb-4">
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Children's Privacy</h2>
          <p className="mb-4">
            Our Service does not address anyone under the age of 18 ("Children").
          </p>
          <p className="mb-4">
            We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
          </p>

          <h2 className="text-2xl font-serif font-bold mt-8 mb-4">Privacy Policy for California Residents</h2>
          <p className="mb-4">
            This Privacy Policy for California Residents section supplements the information above and applies solely to consumers who reside in the State of California ("consumers" or "you"). We adopt this policy to comply with the California Consumer Privacy Act of 2018 (CCPA) and any terms defined in the CCPA have the same meaning when used in this Notice.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Information We Collect</h3>
          <p className="mb-4">
            We collect information that identifies, relates to, describes, references, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer, household, or device ("personal information"). Personal information does not include publicly available information from government records or deidentified or aggregated consumer information.
          </p>
          <p className="mb-4">
            We may have collected the following categories of personal information from our users in the last twelve (12) months:
          </p>

          <div className="overflow-x-auto mb-6">
            <table className="min-w-full border border-border">
              <thead>
                <tr className="bg-muted">
                  <th className="border border-border px-4 py-2 text-left font-bold">Category</th>
                  <th className="border border-border px-4 py-2 text-left font-bold">Collected?</th>
                  <th className="border border-border px-4 py-2 text-left font-bold">Data Collected, If Applicable</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-border px-4 py-2">Identifiers</td>
                  <td className="border border-border px-4 py-2">Yes</td>
                  <td className="border border-border px-4 py-2">Name, alias, postal address, IP address, email address.</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Customer Records Information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Characteristics of protected classifications under California or federal law</td>
                  <td className="border border-border px-4 py-2">Yes</td>
                  <td className="border border-border px-4 py-2">Race, religion, sexual orientation, gender identity, gender expression, age.</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Commercial Information</td>
                  <td className="border border-border px-4 py-2">Yes</td>
                  <td className="border border-border px-4 py-2">Records of subscription boxes purchased (a user's "Have List") or considered (a user's "Wish List"), records of products listed on swap site.</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Biometric information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Internet or other electronic network activity information</td>
                  <td className="border border-border px-4 py-2">Yes</td>
                  <td className="border border-border px-4 py-2">Browsing history, search history, and information regarding a consumer's interaction with an Internet website, application, or advertisement.</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Geolocation data</td>
                  <td className="border border-border px-4 py-2">Yes</td>
                  <td className="border border-border px-4 py-2">IP address</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Audio, electronic, visual, thermal, olfactory, or similar information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Professional or employment related information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Education information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
                <tr>
                  <td className="border border-border px-4 py-2">Inferences drawn from other personal information</td>
                  <td className="border border-border px-4 py-2">No</td>
                  <td className="border border-border px-4 py-2">Not applicable</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Sales of Personal Information</h3>
          <p className="mb-4">
            In the preceding twelve (12) months, Musicatnip LLC has not sold any personal information for commercial purpose or valuable consideration.
          </p>

          <h3 className="text-xl font-serif font-bold mt-6 mb-3">Use of Personal Information & Sharing With Third Parties</h3>
          <p className="mb-4">We may use or disclose the personal information we collect for one or more of the following purposes:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>To allow you to participate in interactive features of our Service when you choose to do so (for example: comments, user reviews, swaps, wishlists, giveaways, product sampling)</li>
            <li>To provide you with a personalized website experience according to your preferences</li>
            <li>To provide you with news, special offers and general information about other goods, services and events that are similar to those that you have already purchased or enquired about, unless you have opted not to receive such information</li>
            <li>To provide, support, develop, and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To provide you with support and respond to your inquiries</li>
            <li>For testing, research, analysis and product development, including to develop and improve our website, products, and services</li>
            <li>To monitor the usage of our website and to detect, prevent and address technical issues</li>
            <li>To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations</li>
          </ul>
          <p className="mb-4">
            We will not collect additional categories of personal information or use the personal information we collected for materially different, unrelated, or incompatible purposes without providing you notice.
          </p>
          <p className="mb-4">
            We work with trusted third parties to perform functions and provide services to us, including but not limited to hosting and maintenance of our website, analytics and monitoring, e-mail marketing, giveaways, product sampling, and user surveys. We may disclose your Personal Information to a third party in order to perform these functions and provide these services. We require these third parties to maintain the privacy and security of the Personal Information they process on our behalf.
          </p>
          <p className="mb-4">
            Users who choose to leave comments or provide written reviews on our website should understand that the text of those comments along with their username or alias (as entered by the user) and URL (if provided) is made publicly available online. E-mail address and IP address are not publicly available and are used for moderation purposes only, but we may contact you via the e-mail you've provided in direct response to submitted comments or reviews.
          </p>

          <p className="text-sm text-muted-foreground mt-8">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
